### Auth - Registro de Usuario
POST http://localhost:3000/api/auth/register 
Content-Type: application/json

{
  "username": "lul",
  "email": "lul@example.com",
  "password": "12345",
  "role": "admin"
}

### Auth - Inicio de Sesión
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "ola@api.com",
  "password": "12345"
}

### Auth - Cerrar Sesión
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgyLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM1OTI1MDEsImV4cCI6MTczMzU5NjEwMX0.OsDmZRFvK9GcfVv4fnXJNy-SEkQ2fN5raG3mnntcqdk
Content-Type: application/json

### Usuarios - Obtener todos los usuarios
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgyLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM1OTI1MDEsImV4cCI6MTczMzU5NjEwMX0.OsDmZRFvK9GcfVv4fnXJNy-SEkQ2fN5raG3mnntcqdk
Content-Type: application/json

### Usuarios - Obtener usuario por ID
GET http://localhost:3000/api/users/360
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgyLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM1OTI1MDEsImV4cCI6MTczMzU5NjEwMX0.OsDmZRFvK9GcfVv4fnXJNy-SEkQ2fN5raG3mnntcqdk
Content-Type: application/json

### Usuarios - Actualizar un usuario por ID
PUT http://localhost:3000/api/users/382
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgyLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM1OTI2NDAsImV4cCI6MTczMzU5NjI0MH0.cO8RpiYxX_53PoByYRlwKwAKCLasIa6r9DdujnHSYRE
Content-Type: application/json

{
  "username": "lulu11_updated",
  "email": "lulu11_updated@example.com"
}

### Usuarios - Eliminar un usuario por ID
DELETE http://localhost:3000/api/users/381
Authorization: Bearer <YOUR_TOKEN>
Content-Type: application/json

### Usuarios - Banear un usuario
POST http://localhost:3000/api/users/366/ban
Authorization: Bearer <YOUR_TOKEN>
Content-Type: application/json

{
  "ban": true
}

### Usuarios - Desbanear un usuario
POST http://localhost:3000/api/users/366/unban
Authorization: Bearer <YOUR_TOKEN>
Content-Type: application/json

{
  "unban": true
}

### Posts - Crear un nuevo post
POST http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM4NTk5MzksImV4cCI6MTczMzg2MzUzOX0._okx76GHbgavv60G-qqG2JgJ6vJ1yA1KAUh7ympacOc
Content-Type: application/json

{
  "title": "My second Post",
  "content": "This is the content of my first post",
  "authorId": 381
}

### Posts - Ver todos los posts
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM5MDcwNzIsImV4cCI6MTczMzkxMDY3Mn0.7_kqqfQLU8mydkppNwAL-oiKhsR-IcQi_MszXvihFZA
### Posts - Ver un post por ID de autor
GET http://localhost:3000/api/posts/author/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM0Mzk2ODg1LCJleHAiOjE3MzQ0MDA0ODV9.jBLo3RluoFmWDDs5hrlZjkVZCEvbqrqMM4r29sC5AsM

### Posts - Actualizar un post por ID
PUT http://localhost:3000/api/posts/40
Authorization: Bearer <YOUR_TOKEN>
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post",
   "authorId": 381
}

### Posts - Eliminar un post por ID
DELETE http://localhost:3000/api/posts/40
Authorization: Bearer <YOUR_TOKEN>
Content-Type: application/json

### Posts - Recuperar un post eliminado
POST http://localhost:3000/api/posts/40/recover
Authorization: Bearer <YOUR_TOKEN>
Content-Type: application/json

### Likes - Crear un like
POST http://localhost:3000/api/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM5MDcwNzIsImV4cCI6MTczMzkxMDY3Mn0.7_kqqfQLU8mydkppNwAL-oiKhsR-IcQi_MszXvihFZA
Content-Type: application/json

{
  "postId": 45
}

### Likes - Eliminar un like
DELETE http://localhost:3000/api/likes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM5MDcwNzIsImV4cCI6MTczMzkxMDY3Mn0.7_kqqfQLU8mydkppNwAL-oiKhsR-IcQi_MszXvihFZA
Content-Type: application/json

{
  "postId": 44
}

### Likes - Contar likes de un post
GET http://localhost:3000/api/likes/count/44
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM5MDcwNzIsImV4cCI6MTczMzkxMDY3Mn0.7_kqqfQLU8mydkppNwAL-oiKhsR-IcQi_MszXvihFZA
Content-Type: application/json

### Posts - Detalles adicionales de posts
GET http://localhost:3000/api/posts/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzgxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzM5MDcwNzIsImV4cCI6MTczMzkxMDY3Mn0.7_kqqfQLU8mydkppNwAL-oiKhsR-IcQi_MszXvihFZA
Content-Type: application/json





 
 



 


 



 











